# Generated by Django 2.1 on 2018-10-05 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpv_persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion_email', models.BooleanField(default=True, help_text='Marque para recibir las notificaciones por correo electrónico', verbose_name='Notificar por Email')),
                ('documentacion_email', models.BooleanField(default=True, help_text='Marque para recibir la documentación por correo electronico', verbose_name='Recibir Documentos por Email')),
                ('datos_personales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_datos', to='dpv_persona.PersonaNatural', verbose_name='Datos Personales')),
                ('datos_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Datos del usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
