# Generated by Django 2.1.2 on 2018-11-05 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpv_persona', '0001_initial'),
        ('dpv_perfil', '0001_initial'),
        ('dpv_nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignedToDepartmentJuridic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(verbose_name='now')),
            ],
        ),
        migrations.CreateModel(
            name='AsignedToDepartmentNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(verbose_name='now')),
            ],
        ),
        migrations.CreateModel(
            name='AsignedToTecnicJuridic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(verbose_name='now')),
            ],
        ),
        migrations.CreateModel(
            name='AsignedToTecnicNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(verbose_name='now')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedency', models.CharField(max_length=50, verbose_name='Procedencia de la Queja')),
                ('body', models.CharField(max_length=1000, verbose_name='Cuerpo de la Queja')),
                ('topic', models.CharField(max_length=200, verbose_name='Titulo de la Queja')),
                ('number', models.CharField(max_length=15, verbose_name='Numero de la Queja')),
                ('status', models.CharField(max_length=15, verbose_name='Estado de la Queja')),
                ('enter_date', models.DateTimeField(verbose_name='Fecha de Introduccion de la Queja')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedComplaintJuridic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_date', models.DateTimeField(verbose_name='now')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedComplaintNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_date', models.DateTimeField(verbose_name='now')),
            ],
        ),
        migrations.CreateModel(
            name='PresentedComplaintJuridic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Complaint', verbose_name='Queja')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_persona.PersonaJuridica', verbose_name='Persona Juridica que Presenta la Queja')),
            ],
        ),
        migrations.CreateModel(
            name='PresentedComplaintNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Complaint', verbose_name='Queja')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_persona.PersonaNatural', verbose_name='Persona Natural que Presenta la Queja')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_perfil.Perfil', verbose_name='Perfil del Tecnico')),
                ('working_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.AreaTrabajo', verbose_name='Area de trabajo del Tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingForDistributionJuridic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(verbose_name='Fecha insertada la queja por persona juridica para esperar la distribucion')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.PresentedComplaintJuridic', verbose_name='Queja')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingForDistributionNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(verbose_name='Fecha insertada la queja por persona natural para esperar la distribucion')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.PresentedComplaintNatural', verbose_name='Queja')),
            ],
        ),
        migrations.AddField(
            model_name='finishedcomplaintnatural',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.PresentedComplaintNatural', verbose_name='Queja por Persona Natural'),
        ),
        migrations.AddField(
            model_name='finishedcomplaintnatural',
            name='tecnic',
            field=models.ManyToManyField(to='dpv_complaint.Tecnic', verbose_name='Tecnico que atendio la Queja Natural'),
        ),
        migrations.AddField(
            model_name='finishedcomplaintjuridic',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.PresentedComplaintJuridic', verbose_name='Queja por Persona Juridica'),
        ),
        migrations.AddField(
            model_name='finishedcomplaintjuridic',
            name='tecnic',
            field=models.ManyToManyField(to='dpv_complaint.Tecnic', verbose_name='Tecnico que atendio la Queja Juridica'),
        ),
        migrations.AddField(
            model_name='asignedtotecnicnatural',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Complaint', verbose_name='Queja por Persona Natural'),
        ),
        migrations.AddField(
            model_name='asignedtotecnicnatural',
            name='tecnic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Tecnic', verbose_name='Tecnico asignado a la Queja Natural'),
        ),
        migrations.AddField(
            model_name='asignedtotecnicjuridic',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Complaint', verbose_name='Queja por Persona Juridica'),
        ),
        migrations.AddField(
            model_name='asignedtotecnicjuridic',
            name='tecnic',
            field=models.ManyToManyField(to='dpv_complaint.Tecnic', verbose_name='Tecnico asignado a la Queja Juridica'),
        ),
        migrations.AddField(
            model_name='asignedtodepartmentnatural',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.PresentedComplaintNatural'),
        ),
        migrations.AddField(
            model_name='asignedtodepartmentnatural',
            name='working_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.AreaTrabajo', verbose_name='Area de Trabajo asignada'),
        ),
        migrations.AddField(
            model_name='asignedtodepartmentjuridic',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.PresentedComplaintJuridic'),
        ),
        migrations.AddField(
            model_name='asignedtodepartmentjuridic',
            name='working_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.AreaTrabajo'),
        ),
    ]
