# Generated by Django 2.1 on 2019-04-09 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpv_persona', '__first__'),
        ('dpv_nomencladores', '__first__'),
        ('dpv_perfil', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_args', models.TextField()),
                ('final_args', models.TextField()),
                ('finished_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer', models.CharField(choices=[('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100)),
                ('boss_accepted', models.ForeignKey(default=False, on_delete=False, related_name='boss_accepted', to='dpv_perfil.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.IntegerField()),
                ('topic', models.CharField(max_length=200, verbose_name='Asunto')),
                ('text', models.CharField(max_length=1000)),
                ('expiration_time', models.IntegerField(default=30)),
                ('entity', models.ForeignKey(on_delete=False, to='dpv_persona.PersonaJuridica')),
                ('made_by', models.ForeignKey(blank=True, on_delete=False, related_name='approach_made_by', to='dpv_persona.PersonaNatural')),
                ('municipality', models.ForeignKey(on_delete=False, to='dpv_nomencladores.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedToTechnician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(default=1, on_delete=False, to='dpv_perfil.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='Origen')),
                ('body', models.TextField(max_length=1000, verbose_name='Cuerpo de la queja')),
                ('topic', models.CharField(max_length=200, verbose_name='Asunto')),
                ('number', models.CharField(max_length=15, verbose_name='Número')),
                ('status', models.CharField(choices=[('Pendiente', 'P'), ('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=20)),
                ('enter_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to_department_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_natural', models.BooleanField(default=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('expiration_time', models.IntegerField(default=60)),
                ('department', models.ForeignKey(null=True, on_delete=False, related_name='department', to='dpv_nomencladores.AreaTrabajo', verbose_name='Departamento')),
                ('person_juridic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_juridic', to='dpv_persona.PersonaJuridica')),
                ('person_natural', models.ForeignKey(blank=True, null=True, on_delete=False, related_name='person_natural', to='dpv_persona.PersonaNatural')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando Asignación', 'Esperando Asignación'), ('Pendiente', 'Pendiente'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=100)),
                ('complaint', models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_args', models.TextField()),
                ('enter_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint', models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_args', models.TextField()),
                ('boss_args', models.TextField()),
                ('final_args', models.TextField(default='')),
                ('boss_answer', models.CharField(blank=True, choices=[('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=20)),
                ('date_of_status', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando Asignación', 'Esperando Asignación'), ('Pendiente', 'Pendiente'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=200)),
                ('is_complaint', models.BooleanField(default=True)),
                ('approach', models.ForeignKey(blank=True, null=True, on_delete=False, to='dpv_complaint.Approach')),
                ('assigned_by', models.ForeignKey(blank=True, default=1, on_delete=False, related_name='assigned_by', to='dpv_perfil.Perfil')),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=False, related_name='boss', to='dpv_perfil.Perfil')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=False, to='dpv_complaint.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='PopularCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=False, related_name='profile', to='dpv_perfil.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingForDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint', models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint')),
            ],
        ),
        migrations.AddField(
            model_name='historycomplaint',
            name='technical',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='technical_history', to='dpv_complaint.Technical'),
        ),
        migrations.AddField(
            model_name='finishedcomplaint',
            name='technical',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Technical'),
        ),
        migrations.AddField(
            model_name='assignedtotechnician',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint'),
        ),
        migrations.AddField(
            model_name='assignedtotechnician',
            name='technical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Technical'),
        ),
        migrations.AddField(
            model_name='approach',
            name='popular_council',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.PopularCouncil'),
        ),
        migrations.AddField(
            model_name='accepted',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint'),
        ),
        migrations.AddField(
            model_name='accepted',
            name='technical_work_in_complaint',
            field=models.ForeignKey(default=1, on_delete=False, related_name='technical_accepted', to='dpv_complaint.Technical'),
        ),
    ]
