# Generated by Django 2.1 on 2019-04-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Finalizada', 'F'), ('Esperando Asignación', 'EA')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Esperando Asignación', 'Esperando Asignación'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Esperando Asignación', 'Esperando Asignación'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=200),
        ),
    ]
