# Generated by Django 2.1 on 2019-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reference',
            field=models.CharField(default='', max_length=50, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='origin',
            field=models.CharField(max_length=50, verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Finalizada', 'F')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada'), ('Esperando Asignación', 'Esperando Asignación'), ('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada'), ('Esperando Asignación', 'Esperando Asignación'), ('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico')], default='Pendiente', max_length=200),
        ),
    ]
