# Generated by Django 2.1.7 on 2019-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P'), ('Finalizada', 'F')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Finalizada', 'Finalizada'), ('Pendiente', 'Pendiente'), ('Esperando Asignación', 'Esperando Asignación')], default='Pendiente', max_length=200),
        ),
    ]
