# Generated by Django 2.1.7 on 2019-03-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('Trámite', 'Trámite'), ('S', 'Solución o Resuelto'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='body',
            field=models.TextField(max_length=1000, verbose_name='Cuerpo de la queja'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('Trámite', 'Trámite'), ('S', 'Solución o Resuelto'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=200),
        ),
    ]
