# Generated by Django 2.1.2 on 2018-12-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0001_initial'),
        ('dpv_persona', '0001_initial'),
        ('dpv_complaint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.IntegerField()),
                ('topic', models.CharField(max_length=200, verbose_name='Titulo')),
                ('text', models.CharField(max_length=1000)),
                ('expiration_time', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConsejoPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='expiration_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('Tramite', 'Tramite'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='body',
            field=models.CharField(max_length=1000, verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(null=True, on_delete=False, related_name='department', to='dpv_nomencladores.AreaTrabajo', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='origin',
            field=models.CharField(max_length=50, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('Tramite', 'Tramite'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA')], default='Pendiente', max_length=200),
        ),
        migrations.AddField(
            model_name='approach',
            name='entity',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Entidad'),
        ),
        migrations.AddField(
            model_name='approach',
            name='made_by',
            field=models.ForeignKey(blank=True, on_delete=False, related_name='approach_made_by', to='dpv_persona.PersonaNatural'),
        ),
        migrations.AddField(
            model_name='approach',
            name='municipality',
            field=models.ForeignKey(on_delete=False, to='dpv_nomencladores.Municipio'),
        ),
        migrations.AddField(
            model_name='approach',
            name='popular_council',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.ConsejoPopular'),
        ),
    ]
