# Generated by Django 2.1 on 2018-11-08 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0001_initial'),
        ('dpv_complaint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsignedToTecnic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_enterDate', models.DateTimeField(verbose_name='now')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_finishedDate', models.DateTimeField(verbose_name='now')),
            ],
        ),
        migrations.CreateModel(
            name='PresentedComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingForDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_enterDate', models.DateTimeField(verbose_name='Fecha insertada la queja por PersonaNatural  para esperar la distribucion')),
                ('_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.PresentedComplaint', verbose_name='Queja')),
            ],
        ),
        migrations.RemoveField(
            model_name='asignedtodepartmentjuridic',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='asignedtodepartmentjuridic',
            name='working_area',
        ),
        migrations.RemoveField(
            model_name='asignedtodepartmentnatural',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='asignedtodepartmentnatural',
            name='working_area',
        ),
        migrations.RemoveField(
            model_name='asignedtotecnicjuridic',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='asignedtotecnicjuridic',
            name='tecnic',
        ),
        migrations.RemoveField(
            model_name='asignedtotecnicnatural',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='asignedtotecnicnatural',
            name='tecnic',
        ),
        migrations.RemoveField(
            model_name='finishedcomplaintjuridic',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='finishedcomplaintjuridic',
            name='tecnic',
        ),
        migrations.RemoveField(
            model_name='finishedcomplaintnatural',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='finishedcomplaintnatural',
            name='tecnic',
        ),
        migrations.RemoveField(
            model_name='presentedcomplaintjuridic',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='presentedcomplaintjuridic',
            name='person',
        ),
        migrations.RemoveField(
            model_name='presentedcomplaintnatural',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='presentedcomplaintnatural',
            name='person',
        ),
        migrations.RemoveField(
            model_name='waitingfordistributionjuridic',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='waitingfordistributionnatural',
            name='complaint',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='body',
            new_name='_body',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='enter_date',
            new_name='_enterDate',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='number',
            new_name='_number',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='procedency',
            new_name='_procedency',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='status',
            new_name='_status',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='topic',
            new_name='_topic',
        ),
        migrations.RenameField(
            model_name='tecnic',
            old_name='perfil',
            new_name='_perfil',
        ),
        migrations.RenameField(
            model_name='tecnic',
            old_name='working_area',
            new_name='_workingArea',
        ),
        migrations.AddField(
            model_name='complaint',
            name='_is',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='AsignedToDepartmentJuridic',
        ),
        migrations.DeleteModel(
            name='AsignedToDepartmentNatural',
        ),
        migrations.DeleteModel(
            name='AsignedToTecnicJuridic',
        ),
        migrations.DeleteModel(
            name='AsignedToTecnicNatural',
        ),
        migrations.DeleteModel(
            name='FinishedComplaintJuridic',
        ),
        migrations.DeleteModel(
            name='FinishedComplaintNatural',
        ),
        migrations.DeleteModel(
            name='PresentedComplaintJuridic',
        ),
        migrations.DeleteModel(
            name='PresentedComplaintNatural',
        ),
        migrations.DeleteModel(
            name='WaitingForDistributionJuridic',
        ),
        migrations.DeleteModel(
            name='WaitingForDistributionNatural',
        ),
        migrations.AddField(
            model_name='presentedcomplaint',
            name='_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Complaint', verbose_name='Queja'),
        ),
        migrations.AddField(
            model_name='presentedcomplaint',
            name='_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_persona.PersonaNatural', verbose_name='PersonaNatural  que Presenta la Queja'),
        ),
        migrations.AddField(
            model_name='finishedcomplaint',
            name='_complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.PresentedComplaint', verbose_name='Queja por PersonaNatural '),
        ),
        migrations.AddField(
            model_name='finishedcomplaint',
            name='_tecnic',
            field=models.ManyToManyField(to='dpv_complaint.Tecnic', verbose_name='Tecnico que atendio la Queja '),
        ),
        migrations.AddField(
            model_name='asignedtotecnic',
            name='_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Complaint', verbose_name='Queja por PersonaNatural '),
        ),
        migrations.AddField(
            model_name='asignedtotecnic',
            name='_tecnic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Tecnic', verbose_name='Tecnico asignado a la Queja '),
        ),
        migrations.AddField(
            model_name='accepted',
            name='_complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.PresentedComplaint', verbose_name='Queja por PersonaNatural '),
        ),
    ]
