# Generated by Django 2.1.2 on 2018-12-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0002_auto_20181212_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('Tramite', 'Tramite'), ('ECNS', 'Explicada Causa de no Solucion'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('Tramite', 'Tramite'), ('ECNS', 'Explicada Causa de no Solucion'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=200),
        ),
    ]
