# Generated by Django 2.1 on 2019-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0002_auto_20190407_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('S', 'Solución o Resuelto'), ('Trámite', 'Trámite'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='origin',
            field=models.CharField(default='', max_length=50, verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'ERT'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA'), ('Finalizada', 'F'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'Finalizada'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Esperando Asignación', 'Esperando Asignación'), ('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('S', 'Solución o Resuelto'), ('Trámite', 'Trámite'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'Finalizada'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Esperando Asignación', 'Esperando Asignación'), ('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico')], default='Pendiente', max_length=200),
        ),
    ]
