# Generated by Django 2.1.7 on 2019-03-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_perfil', '0001_initial'),
        ('dpv_complaint', '0002_auto_20190319_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtotechnician',
            name='assigned_by',
            field=models.ForeignKey(default=1, on_delete=False, to='dpv_perfil.Perfil'),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solución'), ('PR', 'Pendiente de Respuesta'), ('Trámite', 'Trámite'), ('PS', 'Pendiente de Solución'), ('S', 'Solución o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solución'), ('PR', 'Pendiente de Respuesta'), ('Trámite', 'Trámite'), ('PS', 'Pendiente de Solución'), ('S', 'Solución o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=200),
        ),
    ]
