# Generated by Django 2.1 on 2019-04-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0002_auto_20190410_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('Trámite', 'Trámite'), ('S', 'Solución o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'ERT'), ('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignación', 'EA')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('Esperando Asignación', 'Esperando Asignación'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('Trámite', 'Trámite'), ('S', 'Solución o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada'), ('Esperando Asignación', 'Esperando Asignación'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe')], default='Pendiente', max_length=200),
        ),
    ]
