# Generated by Django 2.1.2 on 2018-11-13 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_perfil', '0002_auto_20181109_1608'),
        ('dpv_persona', '0001_initial'),
        ('dpv_complaint', '0002_auto_20181108_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Queja'},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='_is',
        ),
        migrations.RemoveField(
            model_name='finishedcomplaint',
            name='_finishedDate',
        ),
        migrations.RemoveField(
            model_name='presentedcomplaint',
            name='_person',
        ),
        migrations.RemoveField(
            model_name='tecnic',
            name='_workingArea',
        ),
        migrations.AddField(
            model_name='accepted',
            name='_argumentsOfTecnic',
            field=models.CharField(default='', max_length=1000, verbose_name='Respuesta del tecnico a la queja'),
        ),
        migrations.AddField(
            model_name='accepted',
            name='_bossAccepted',
            field=models.ForeignKey(default=False, on_delete=False, to='dpv_perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='accepted',
            name='_finalArgumnets',
            field=models.CharField(default='', max_length=1000, verbose_name='Respuesta final del jefe a la queja'),
        ),
        migrations.AddField(
            model_name='accepted',
            name='_finishedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 1, 48, 54, 802206, tzinfo=utc), verbose_name='now'),
        ),
        migrations.AddField(
            model_name='accepted',
            name='_tecnicWorkInComplaint',
            field=models.ManyToManyField(to='dpv_complaint.Tecnic', verbose_name='Tecnico que atendio la Queja '),
        ),
        migrations.AddField(
            model_name='complaint',
            name='_is_natural',
            field=models.BooleanField(default=True, verbose_name='Es Natural'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='_person_juridic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpv_persona.PersonaJuridica', verbose_name='Persona Natural  que Presenta la Queja'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='_person_natural',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpv_persona.PersonaNatural', verbose_name='Persona Natural  que Presenta la Queja'),
        ),
        migrations.AddField(
            model_name='finishedcomplaint',
            name='_arguments',
            field=models.CharField(default='', max_length=1000, verbose_name='Respuesta del tecnico a la queja'),
        ),
        migrations.AddField(
            model_name='finishedcomplaint',
            name='_enterDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 1, 48, 54, 801292, tzinfo=utc), verbose_name='now'),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='_complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint', verbose_name='Queja por PersonaNatural '),
        ),
        migrations.AlterField(
            model_name='asignedtotecnic',
            name='_enterDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 1, 48, 54, 790298, tzinfo=utc), verbose_name='Now'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='_enterDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 1, 48, 54, 788708, tzinfo=utc), verbose_name='Fecha de Introduccion de la Queja'),
        ),
        migrations.AlterField(
            model_name='finishedcomplaint',
            name='_complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint', verbose_name='Queja por PersonaNatural '),
        ),
        migrations.AlterField(
            model_name='waitingfordistribution',
            name='_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpv_complaint.Complaint', verbose_name='Queja'),
        ),
        migrations.AlterField(
            model_name='waitingfordistribution',
            name='_enterDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 1, 48, 54, 789904, tzinfo=utc), verbose_name='Fecha insertada la queja por PersonaNatural  para esperar la distribucion'),
        ),
    ]
