# Generated by Django 2.1.7 on 2019-03-20 22:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0003_auto_20190320_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_to_department_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 20, 22, 34, 37, 99630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solución'), ('Trámite', 'Trámite'), ('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solución'), ('Trámite', 'Trámite'), ('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=200),
        ),
    ]
