# Generated by Django 2.1 on 2019-04-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0003_auto_20190424_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Pendiente', 'P'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando Asignación', 'Esperando Asignación')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando Asignación', 'Esperando Asignación')], default='Pendiente', max_length=200),
        ),
    ]
