# Generated by Django 2.1.2 on 2018-11-13 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0003_auto_20181113_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='_finishedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='now'),
        ),
        migrations.AlterField(
            model_name='asignedtotecnic',
            name='_enterDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Now'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='_enterDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Introduccion de la Queja'),
        ),
        migrations.AlterField(
            model_name='finishedcomplaint',
            name='_enterDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='now'),
        ),
        migrations.AlterField(
            model_name='waitingfordistribution',
            name='_enterDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha insertada la queja por PersonaNatural  para esperar la distribucion'),
        ),
    ]
