# Generated by Django 2.1 on 2019-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0004_auto_20190424_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accepted',
            options={'verbose_name': 'Queja Aceptada', 'verbose_name_plural': 'Queja Acceptada'},
        ),
        migrations.AlterModelOptions(
            name='approach',
            options={'verbose_name': 'Planteamiento', 'verbose_name_plural': 'Planteamientos'},
        ),
        migrations.AlterModelOptions(
            name='assignedtotechnician',
            options={'verbose_name': 'Queja asignadas a técnicos', 'verbose_name_plural': 'Queja asignadas a técnicos'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Queja', 'verbose_name_plural': 'Quejas'},
        ),
        migrations.AlterModelOptions(
            name='currentcomplaint',
            options={'verbose_name': 'Queja en Proceso', 'verbose_name_plural': 'Quejas en Proceso'},
        ),
        migrations.AlterModelOptions(
            name='finishedcomplaint',
            options={'verbose_name': '', 'verbose_name_plural': 'Queja Finalizada'},
        ),
        migrations.AlterModelOptions(
            name='historycomplaint',
            options={'verbose_name': 'Histórico', 'verbose_name_plural': 'Históricos'},
        ),
        migrations.AlterModelOptions(
            name='popularcouncil',
            options={'verbose_name': 'Consejo Popular', 'verbose_name_plural': 'Consejos Populares'},
        ),
        migrations.AlterModelOptions(
            name='technical',
            options={'verbose_name': 'Técnicos', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='waitingfordistribution',
            options={'verbose_name': 'Queja esperando distribución', 'verbose_name_plural': 'Queja esperando distribución'},
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('S', 'Solución o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignación', 'EA'), ('Esperando Respuesta de Técnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'Esperando Asignación'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Pendiente', 'Pendiente'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('PR', 'Pendiente de Respuesta'), ('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('S', 'Solución o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'Esperando Asignación'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Pendiente', 'Pendiente'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=200),
        ),
    ]
