# Generated by Django 2.1 on 2019-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0004_auto_20190410_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solución'), ('PR', 'Pendiente de Respuesta'), ('Trámite', 'Trámite'), ('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Respuesta de Técnico', 'ERT'), ('Finalizada', 'F')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'Finalizada'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando Asignación', 'Esperando Asignación'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('ECNS', 'Explicada Causa de no Solución'), ('PR', 'Pendiente de Respuesta'), ('Trámite', 'Trámite'), ('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'Finalizada'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando Asignación', 'Esperando Asignación'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=200),
        ),
    ]
