# Generated by Django 2.1 on 2019-04-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0004_auto_20190407_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solución'), ('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('S', 'Solución o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'ERT'), ('Finalizada', 'F'), ('Pendiente', 'P'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Finalizada', 'Finalizada'), ('Esperando Asignación', 'Esperando Asignación'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('ECNS', 'Explicada Causa de no Solución'), ('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite'), ('S', 'Solución o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Finalizada', 'Finalizada'), ('Esperando Asignación', 'Esperando Asignación'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe')], default='Pendiente', max_length=200),
        ),
    ]
