# Generated by Django 2.1.7 on 2019-03-20 23:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0004_auto_20190320_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historycomplaint',
            name='state',
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_to_department_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 20, 23, 17, 8, 835764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Finalizada', 'F'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('Trámite', 'Trámite'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Finalizada', 'F'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=200),
        ),
    ]
