# Generated by Django 2.1.2 on 2018-12-14 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0004_auto_20181212_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PS', 'Pendiente de Solucion'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solucion'), ('S', 'Solucion o Resuelto'), ('Tramite', 'Tramite')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='person_juridic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_juridic', to='dpv_persona.PersonaJuridica'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='person_natural',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='person_natural', to='dpv_persona.PersonaNatural'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Pendiente', 'P'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando Asignacion', 'EA'), ('Esperando aceptacion del jefe', 'EAJ')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('PS', 'Pendiente de Solucion'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solucion'), ('S', 'Solucion o Resuelto'), ('Tramite', 'Tramite')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Pendiente', 'P'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando Asignacion', 'EA'), ('Esperando aceptacion del jefe', 'EAJ')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Pendiente', 'P'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando Asignacion', 'EA'), ('Esperando aceptacion del jefe', 'EAJ')], default='Pendiente', max_length=200),
        ),
    ]
