# Generated by Django 2.1 on 2019-04-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0005_auto_20190407_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('Trámite', 'Trámite'), ('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Pendiente', 'P'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada'), ('Pendiente', 'Pendiente'), ('Esperando Asignación', 'Esperando Asignación')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('Trámite', 'Trámite'), ('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Finalizada', 'Finalizada'), ('Pendiente', 'Pendiente'), ('Esperando Asignación', 'Esperando Asignación')], default='Pendiente', max_length=200),
        ),
    ]
