# Generated by Django 2.1 on 2019-04-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0005_auto_20190426_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['enter_date'], 'verbose_name': 'Queja', 'verbose_name_plural': 'Quejas'},
        ),
        migrations.AlterModelOptions(
            name='technical',
            options={'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('S', 'Solución o Resuelto'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('Trámite', 'Trámite')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='approach',
            name='popular_council',
            field=models.ForeignKey(on_delete=False, to='dpv_nomencladores.ConsejoPopular'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Esperando Respuesta de Técnico', 'ERT'), ('Finalizada', 'F')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentcomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'Esperando Asignación'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('S', 'Solución o Resuelto'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('Trámite', 'Trámite')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'Esperando Asignación'), ('Esperando aceptación del jefe', 'Esperando aceptación del jefe'), ('Esperando Respuesta de Técnico', 'Esperando Respuesta de Técnico'), ('Pendiente', 'Pendiente'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=200),
        ),
        migrations.DeleteModel(
            name='PopularCouncil',
        ),
    ]
