# Generated by Django 2.1.7 on 2019-03-20 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_perfil', '0001_initial'),
        ('dpv_complaint', '0005_auto_20190320_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='historycomplaint',
            name='approach',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='dpv_complaint.Approach'),
        ),
        migrations.AddField(
            model_name='historycomplaint',
            name='assigned_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=False, related_name='assigned_by', to='dpv_perfil.Perfil'),
        ),
        migrations.AddField(
            model_name='historycomplaint',
            name='final_args',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historycomplaint',
            name='is_complaint',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_to_department_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss',
            field=models.ForeignKey(blank=True, on_delete=False, related_name='boss', to='dpv_perfil.Perfil'),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(blank=True, choices=[('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solución'), ('S', 'Solución o Resuelto'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='dpv_complaint.Complaint'),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=200),
        ),
    ]
