# Generated by Django 2.1.2 on 2018-12-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0006_auto_20181214_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PS', 'Pendiente de Solucion'), ('S', 'Solucion o Resuelto'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta'), ('Tramite', 'Tramite')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Asignacion', 'EA'), ('Pendiente', 'P'), ('Esperando aceptacion del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('PS', 'Pendiente de Solucion'), ('S', 'Solucion o Resuelto'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta'), ('Tramite', 'Tramite')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignacion', 'EA'), ('Pendiente', 'P'), ('Esperando aceptacion del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Esperando Asignacion', 'EA'), ('Pendiente', 'P'), ('Esperando aceptacion del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=200),
        ),
    ]
