# Generated by Django 2.1.2 on 2018-11-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0006_auto_20181115_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'ECNS'), ('S', 'S'), ('Tramite', 'Tramite'), ('PS', 'PS'), ('PR', 'PR')], default='S', max_length=100, verbose_name='Actual Respuesta de la queja'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('EAJ', 'Esperando aceptacion del jefe'), ('P', 'Pendiente'), ('EA', 'Esperando Asignacion'), ('ERT', 'Esperando Respuesta de Tecnico')], default='Pendiente', max_length=15, verbose_name='Estado de la Queja'),
        ),
    ]
