# Generated by Django 2.1.2 on 2018-11-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0007_auto_20181115_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentedcomplaint',
            name='complaint',
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'ECNS'), ('S', 'S'), ('Tramite', 'Tramite'), ('PR', 'PR'), ('PS', 'PS')], default='S', max_length=100, verbose_name='Actual Respuesta de la queja'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('ERT', 'Esperando Respuesta de Tecnico'), ('P', 'Pendiente'), ('EAJ', 'Esperando aceptacion del jefe'), ('EA', 'Esperando Asignacion')], default='Pendiente', max_length=15, verbose_name='Estado de la Queja'),
        ),
        migrations.RemoveField(
            model_name='finishedcomplaint',
            name='tecnic',
        ),
        migrations.AddField(
            model_name='finishedcomplaint',
            name='tecnic',
            field=models.ForeignKey(default=1, on_delete=False, to='dpv_complaint.Tecnic', verbose_name='Tecnico que atendio la Queja '),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PresentedComplaint',
        ),
    ]
