# Generated by Django 2.1.7 on 2019-02-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0007_auto_20181214_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepted',
            old_name='technical_work_in_complaint',
            new_name='technical',
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('Tramite', 'Tramite'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint', unique=True),
        ),
        migrations.AlterField(
            model_name='assignedtotechnician',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint', unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Esperando aceptacion del jefe', 'EAJ')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='finishedcomplaint',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint', unique=True),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('Tramite', 'Tramite'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Esperando aceptacion del jefe', 'EAJ')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Esperando aceptacion del jefe', 'EAJ')], default='Pendiente', max_length=200),
        ),
        migrations.AlterField(
            model_name='waitingfordistribution',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint', unique=True),
        ),
    ]
