# Generated by Django 2.1.7 on 2019-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0008_auto_20190225_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accepted',
            old_name='technical',
            new_name='technical_work_in_complaint',
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solucion'), ('Tramite', 'Tramite'), ('PS', 'Pendiente de Solucion'), ('S', 'Solucion o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptacion del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('ECNS', 'Explicada Causa de no Solucion'), ('Tramite', 'Tramite'), ('PS', 'Pendiente de Solucion'), ('S', 'Solucion o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptacion del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando aceptacion del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=200),
        ),
    ]
