# Generated by Django 2.1.2 on 2018-11-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0008_auto_20181116_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PS', 'PS'), ('S', 'S'), ('ECNS', 'ECNS'), ('PR', 'PR'), ('Tramite', 'Tramite')], default='S', max_length=100, verbose_name='Actual Respuesta de la queja'),
        ),
        migrations.RemoveField(
            model_name='accepted',
            name='tecnicWorkInComplaint',
        ),
        migrations.AddField(
            model_name='accepted',
            name='tecnicWorkInComplaint',
            field=models.ForeignKey(default=1, on_delete=False, to='dpv_complaint.Tecnic', verbose_name='Tecnico que atendio la Queja '),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('EA', 'Esperando Asignacion'), ('P', 'Pendiente'), ('ERT', 'Esperando Respuesta de Tecnico'), ('EAJ', 'Esperando aceptacion del jefe')], default='Pendiente', max_length=15, verbose_name='Estado de la Queja'),
        ),
    ]
