# Generated by Django 2.1.7 on 2019-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0009_auto_20190227_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('Tramite', 'Tramite'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando aceptacion del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('Tramite', 'Tramite'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptacion del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Esperando aceptacion del jefe', 'EAJ'), ('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=200),
        ),
    ]
