# Generated by Django 2.1.7 on 2019-02-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0010_auto_20190228_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('Tramite', 'Tramite'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('ECNS', 'Explicada Causa de no Solucion')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('Tramite', 'Tramite'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('ECNS', 'Explicada Causa de no Solucion')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=200),
        ),
    ]
