# Generated by Django 2.1.2 on 2018-11-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0010_auto_20181119_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solucion'), ('Tramite', 'Tramite'), ('S', 'Solucion o Resuelto')], default='S', max_length=100, verbose_name='Actual Respuesta de la queja'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P')], default='Pendiente', max_length=20, verbose_name='Estado de la Queja'),
        ),
    ]
