# Generated by Django 2.1.2 on 2018-11-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0002_auto_20181109_1603'),
        ('dpv_complaint', '0011_auto_20181119_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(default=0, null=True, on_delete=False, to='dpv_nomencladores.AreaTrabajo'),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('Tramite', 'Tramite'), ('ECNS', 'Explicada Causa de no Solucion'), ('PS', 'Pendiente de Solucion'), ('S', 'Solucion o Resuelto'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100, verbose_name='Actual Respuesta de la queja'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Esperando Asignacion', 'EA'), ('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20, verbose_name='Estado de la Queja'),
        ),
    ]
