# Generated by Django 2.1.7 on 2019-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0012_auto_20190317_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solucion'), ('Tramite', 'Tramite'), ('PS', 'Pendiente de Solucion'), ('PR', 'Pendiente de Respuesta'), ('S', 'Solucion o Resuelto')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='accepted',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint'),
        ),
        migrations.AlterField(
            model_name='assignedtotechnician',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='finishedcomplaint',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint'),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('ECNS', 'Explicada Causa de no Solucion'), ('Tramite', 'Tramite'), ('PS', 'Pendiente de Solucion'), ('PR', 'Pendiente de Respuesta'), ('S', 'Solucion o Resuelto')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=200),
        ),
        migrations.AlterField(
            model_name='waitingfordistribution',
            name='complaint',
            field=models.ForeignKey(on_delete=False, to='dpv_complaint.Complaint'),
        ),
    ]
