# Generated by Django 2.1.2 on 2018-11-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0012_auto_20181119_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('Tramite', 'Tramite'), ('S', 'Solucion o Resuelto'), ('PS', 'Pendiente de Solucion'), ('ECNS', 'Explicada Causa de no Solucion'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100, verbose_name='Actual Respuesta de la queja'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(null=True, on_delete=False, to='dpv_nomencladores.AreaTrabajo'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Respuesta de Tecnico', 'ERT'), ('Esperando Asignacion', 'EA'), ('Pendiente', 'P'), ('Esperando aceptacion del jefe', 'EAJ')], default='Pendiente', max_length=20, verbose_name='Estado de la Queja'),
        ),
    ]
