# Generated by Django 2.1.2 on 2018-11-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0013_auto_20181119_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('S', 'Solucion o Resuelto'), ('ECNS', 'Explicada Causa de no Solucion'), ('PS', 'Pendiente de Solucion'), ('Tramite', 'Tramite'), ('PR', 'Pendiente de Respuesta')], default='S', max_length=100, verbose_name='Actual Respuesta de la queja'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'P'), ('Esperando aceptacion del jefe', 'EAJ'), ('Esperando Asignacion', 'EA'), ('Esperando Respuesta de Tecnico', 'ERT')], default='Pendiente', max_length=20, verbose_name='Estado de la Queja'),
        ),
    ]
