# Generated by Django 2.1.7 on 2019-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0013_auto_20190318_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto'), ('ECNS', 'Explicada Causa de no Solución'), ('Trámite', 'Trámite')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='approach',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='body',
            field=models.CharField(max_length=1000, verbose_name='Cuerpo de la queja'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('PS', 'Pendiente de Solución'), ('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto'), ('ECNS', 'Explicada Causa de no Solución'), ('Trámite', 'Trámite')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Finalizada', 'F'), ('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P')], default='Pendiente', max_length=200),
        ),
    ]
