# Generated by Django 2.1.7 on 2019-03-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0014_auto_20190319_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsejoPopular',
            new_name='PopularCouncil',
        ),
        migrations.RenameField(
            model_name='popularcouncil',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('S', 'Solución o Resuelto'), ('Trámite', 'Trámite'), ('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solución'), ('ECNS', 'Explicada Causa de no Solución')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('S', 'Solución o Resuelto'), ('Trámite', 'Trámite'), ('PR', 'Pendiente de Respuesta'), ('PS', 'Pendiente de Solución'), ('ECNS', 'Explicada Causa de no Solución')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Esperando Asignación', 'EA'), ('Esperando aceptación del jefe', 'EAJ'), ('Finalizada', 'F'), ('Esperando Respuesta de Técnico', 'ERT'), ('Pendiente', 'P')], default='Pendiente', max_length=200),
        ),
    ]
