# Generated by Django 2.1.7 on 2019-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_complaint', '0015_auto_20190319_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accepted',
            name='answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite')], default='S', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='boss_answer',
            field=models.CharField(choices=[('PR', 'Pendiente de Respuesta'), ('S', 'Solución o Resuelto'), ('ECNS', 'Explicada Causa de no Solución'), ('PS', 'Pendiente de Solución'), ('Trámite', 'Trámite')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='current_status',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historycomplaint',
            name='state',
            field=models.CharField(choices=[('Esperando aceptación del jefe', 'EAJ'), ('Esperando Respuesta de Técnico', 'ERT'), ('Esperando Asignación', 'EA'), ('Pendiente', 'P'), ('Finalizada', 'F')], default='Pendiente', max_length=200),
        ),
    ]
