# Generated by Django 2.1 on 2019-02-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_locales', '0001_initial'),
        ('dpv_viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='add_concepto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Datos Concepto'),
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together={('numero', 'local_dado')},
        ),
    ]
