# Generated by Django 2.1 on 2018-11-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='concepto',
            field=models.ForeignKey(help_text='Concepto de uso de la vivienda', on_delete=django.db.models.deletion.CASCADE, to='dpv_nomencladores.Concepto', verbose_name='Concepto'),
        ),
        migrations.DeleteModel(
            name='Concepto',
        ),
    ]
