# Generated by Django 2.1 on 2018-11-09 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_locales', '0001_initial'),
        ('dpv_viviendas', '0002_auto_20181109_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='local_dado',
            field=models.ForeignKey(default='', help_text='Local donde se encuentra la vivienda.', on_delete=django.db.models.deletion.CASCADE, related_name='vivienda_local', to='dpv_locales.Local'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='aprobada',
            field=models.BooleanField(default=False, help_text='Marcar si la vivienda esta aprobada.', verbose_name='Aprobación dada'),
        ),
    ]
