# Generated by Django 2.1 on 2018-12-09 06:46

import apps.dpv_locales.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_locales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='acuerdoCAM',
            field=models.CharField(blank=True, default='', max_length=9, validators=[apps.dpv_locales.validators.validate_acta_acuerdo], verbose_name='Acuerdo CAM'),
        ),
        migrations.AlterField(
            model_name='local',
            name='acuerdoORG',
            field=models.CharField(blank=True, default='', max_length=9, validators=[apps.dpv_locales.validators.validate_acta_acuerdo], verbose_name='Acuerdo Organismo'),
        ),
        migrations.AlterField(
            model_name='local',
            name='acuerdoPEM',
            field=models.CharField(blank=True, default='', max_length=9, validators=[apps.dpv_locales.validators.validate_acta_acuerdo], verbose_name='Acuerdo PEM'),
        ),
        migrations.AlterField(
            model_name='local',
            name='acuerdo_DPV',
            field=models.CharField(blank=True, default='', max_length=9, unique=True, validators=[apps.dpv_locales.validators.validate_acta_acuerdo], verbose_name='Acuerdo DPV'),
        ),
    ]
