# Generated by Django 2.1 on 2018-12-09 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_locales', '0002_auto_20181209_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='direccion_numero',
            field=models.CharField(help_text='Numero de la dirección', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]', message='Este campo debe comenzar por un número.')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='local',
            name='no_viviendas',
            field=models.PositiveSmallIntegerField(help_text='Total de viviendas en el local', validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Total de viviendas'),
        ),
        migrations.AlterField(
            model_name='local',
            name='pendiente',
            field=models.PositiveSmallIntegerField(help_text='Viviendas pendientes de aprobación', validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Pendientes de aprobación'),
        ),
    ]
