# Generated by Django 2.1 on 2018-12-22 19:32

import apps.dpv_locales.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_locales', '0003_auto_20181209_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='acuerdo_DPV',
            field=models.CharField(blank=True, default='', max_length=9, validators=[apps.dpv_locales.validators.validate_acta_acuerdo], verbose_name='Acuerdo DPV'),
        ),
    ]
