# Generated by Django 2.1 on 2018-12-22 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_locales', '0004_auto_20181222_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='data_ok',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='local',
            name='system_info',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
