# Generated by Django 2.1.4 on 2019-01-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(max_length=100)),
                ('puerto', models.CharField(max_length=3)),
                ('usuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('usa_tls', models.BooleanField(default=False)),
                ('usa_ssl', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración de correo',
            },
        ),
    ]
