# Generated by Django 2.1 on 2019-04-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calle',
            name='municipios',
        ),
    ]
