# Generated by Django 2.1 on 2018-12-30 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Área de Trabajo'),
        ),
        migrations.AlterField(
            model_name='calle',
            name='nombre',
            field=models.CharField(help_text='Nombre de la calle', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='nombre',
            field=models.CharField(help_text='Nombre de la unidad.', max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Centro de trabajo'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='siglas',
            field=models.CharField(help_text='Siglas de la entidad.', max_length=5, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='nombre',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='consejopopular',
            name='nombre',
            field=models.CharField(help_text='Nombre del consejo popular', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Consejo Popular'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(help_text='Identificador del destino', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(help_text='Nombre del municipio', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre',
            field=models.CharField(help_text='Nombre del organismo.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name=' Organismo'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='siglas',
            field=models.CharField(help_text='Siglas representativas del organismo', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")]),
        ),
        migrations.AlterField(
            model_name='piso',
            name='nombre',
            field=models.CharField(help_text='Nombre del piso', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(help_text='Nombre del municipio', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9 ]', message="Este campos no puede contener caracteres especiales, ejem. '@', '#', '!', '.', '%', ")], verbose_name='Provincia'),
        ),
    ]
