# Generated by Django 2.1 on 2018-12-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0002_auto_20181109_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='numero',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Número'),
        ),
    ]
