# Generated by Django 2.1 on 2019-04-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0002_remove_calle_municipios'),
    ]

    operations = [
        migrations.AddField(
            model_name='calle',
            name='municipios',
            field=models.ManyToManyField(blank=True, default='', help_text='Municipios en los que esta presente una calle con este nombre.', to='dpv_nomencladores.Municipio', verbose_name='Municipios'),
        ),
    ]
