# Generated by Django 2.1 on 2018-12-09 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_nomencladores', '0002_auto_20181109_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='numero',
            field=models.CharField(blank=True, max_length=3, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números')], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='sigla',
            field=models.CharField(max_length=1, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(1), django.core.validators.RegexValidator('^[a-zA-Z ]*[a-zA-Z ]$', message='Este campo solo puede contener letras')], verbose_name='Inicial'),
        ),
    ]
