# Generated by Django 2.1 on 2018-12-14 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator('[a-zA-Z]', message='Este campo solo puede contener letras')]),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='apellidos',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator('[a-zA-Z]', message='Este campo solo puede contener letras')]),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator('[a-zA-Z]', message='Este campo solo puede contener letras')]),
        ),
    ]
