# Generated by Django 2.1 on 2019-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0002_auto_20190424_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='direccion_numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='direccion_numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
