# Generated by Django 2.1 on 2018-12-09 20:37

import apps.dpv_persona.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpv_persona', '0002_auto_20181209_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajuridica',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='personanatural',
            name='ci',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='Este campo no puede tener menos de 11 caracteres'), django.core.validators.MaxLengthValidator(11, message='Este campo no puede tener más de 11 caracteres'), django.core.validators.RegexValidator('^[0-9]*[0-9]$', message='Este campo solo puede contener números'), apps.dpv_persona.validators.ci_validate]),
        ),
    ]
