# Generated by Django 2.1 on 2018-12-22 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfigurate',
            options={'ordering': ['servidor'], 'verbose_name': 'COnfiguración de Correo', 'verbose_name_plural': 'Configuraciones de Correo'},
        ),
        migrations.AlterField(
            model_name='emailconfigurate',
            name='password',
            field=models.CharField(blank=True, help_text='Contraseña del usuario para authenticarse en el servidor.', max_length=50, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(50)], verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='emailconfigurate',
            name='puerto',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Puerto de conección al servidor.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Puerto'),
        ),
        migrations.AlterField(
            model_name='emailconfigurate',
            name='usuario',
            field=models.CharField(blank=True, help_text='Usuario para autenticarse en el servidor', max_length=255, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(255)], verbose_name='Usuario'),
        ),
    ]
